{% set name = "psy-reg" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_BUILD_STR', '') }}{% if environ.get('GIT_BRANCH') %}_{{ environ.get('GIT_BRANCH') }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 27]

requirements:
  build:
  - python
  - pip
  run:
  - python
  - psyplot
  - psy-simple
  - statsmodels
  - scipy

test:
  imports:
  - psy_reg

about:
  home: https://github.com/Chilipp/psy-reg
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualizing and calculating regression plots

  description: |
    This psyplot plugin can be used to make fits to your data and visualize
    them
  doc_url: http://psyplot.readthedocs.io/projects/psy-reg
dev_url: https://github.com/Chilipp/psy-reg
